Master spring 1.1
vaadin/spring-demo7 pull request #1
Opened 2016-10-19 11:06 UTC by elmot

Refactor project to be able to test different Spring approaches

2016-10-19 11:30 UTC, hesara reviewed
Various comments

2016-10-19 11:30 UTC, hesara commented on spring-demo-ui-legacy-boot/pom.xml
> +                <version>${vaadin.version}</version>
instead of dependency management for a single Vaadin JAR, ahould use the vaadin-bom

2016-10-19 11:30 UTC, hesara commented on spring-demo-ui-legacy-boot/pom.xml
> +            version. 1.4.0 Spring boot doesn't work with with Vaadin Spring boot. -->
Is this still true? What is the problem with 1.4? We should probably fix that and use 1.4.1 rather than making workarounds.

2016-10-19 11:30 UTC, hesara commented on spring-demo-ui-legacy-boot/pom.xml
> +                <version>1.3.2.RELEASE</version>
old version? parametrize all instances of Spring Boot version?

2016-10-19 11:30 UTC, hesara commented on spring-demo-ui/pom.xml
>          <!-- This version is important regarding used Vaadin plugin versions
Is this comment valid anymore? What is the commented out section below?

2016-10-19 11:30 UTC, hesara commented on spring-demo-ui/src/main/java/com/vaadin/framework7/samples/crud/SampleCrudLogic.java
> +@Scope/*(scopeName = ConfigurableBeanFactory.SCOPE_SINGLETON)*/
Why not a singleton anymore? What scope does this imply without any parameters?

2016-10-19 11:30 UTC, hesara commented on spring-demo-ui/src/main/java/com/vaadin/framework7/samples/crud/SampleCrudLogic.java
> +    private AccessControl accessControl;
This can only work correctly if the scope above is a correct Vaadin scope.

2016-10-19 13:55 UTC, elmot commented on spring-demo-ui-legacy-boot/pom.xml
> +                <version>${vaadin.version}</version>
Done

2016-10-19 13:55 UTC, elmot commented on spring-demo-ui-legacy-boot/pom.xml
> +                <version>1.3.2.RELEASE</version>
Done

2016-10-19 14:18 UTC, elmot commented on spring-demo-ui/src/main/java/com/vaadin/framework7/samples/crud/SampleCrudLogic.java
> +    private AccessControl accessControl;
Done

2016-10-21 08:21 UTC, hesara requested changes

2016-10-21 08:21 UTC, hesara commented on pom.xml
> +                <groupId>com.vaadin.framework7</groupId>
where is this? in the same project?

2016-10-21 08:21 UTC, hesara commented on .travis.yml
> -branches:
should enable reviewable and CLA Assistant, and protect master branch

2016-10-21 08:21 UTC, hesara commented on pom.xml
> +                <type>pom</type>
bom import should also always have <scope>import</scope>

2016-10-21 08:21 UTC, hesara commented on spring-demo-ui-legacy-boot/pom.xml
> +                <exclusion>
exclusions and explicit import probably not necessary - I don't think we need anything else than spring-demo-backend and vaadin-spring-boot-starter as explicit compile scope dependencies

2016-10-21 08:21 UTC, hesara commented on spring-demo-ui-legacy-boot/pom.xml
> +        <dependency>
BOM should always be imported with the special approach (type pom, scope import in dependencyManagement IIRC)

2016-10-21 08:21 UTC, hesara commented on spring-demo-ui-legacy-boot/pom.xml
> +        <dependency>
why import type war and classifier classes?

2016-10-21 08:21 UTC, hesara commented on spring-demo-ui-legacy-boot/pom.xml
> +                    <!-- By attaching the classes to a separate JAR, we can
does the project have a production mode module? if not, the related parts can probably be deleted here

2016-10-21 08:21 UTC, hesara commented on spring-demo-ui/pom.xml
> -    <dependencyManagement>
this was correct, explicitly importing a BOM as a normal dependency is not - BOMs are special

2016-10-21 08:21 UTC, hesara commented on spring-demo-ui/pom.xml
>          <dependency>
see the comment above about BOMs

2016-10-21 08:47 UTC, elmot commented on pom.xml
> +                <groupId>com.vaadin.framework7</groupId>
Yes. another subproject of the same root. That is just a copy from fw8 spring demo.

2016-10-21 10:11 UTC, elmot commented on .travis.yml
> -branches:
Done, Both CLA, Reviewable and protected master.

2016-10-21 10:51 UTC, elmot commented
Review status: 0 of 10 files reviewed at latest revision, 13 unresolved discussions, some commit checks failed.

---

*[pom.xml, line 158 at r2](https://reviewable.io:443/reviews/vaadin/spring-demo7/1#-KUaRBMdkwhJ0Lbgek6w-r2-158:-KUarHrvy3Wpttdfi7JH:b-lw8iyf) ([raw file](https://github.com/vaadin/spring-demo7/blob/838ea76dd700cabf7371fc658a433bc7cb49e38a/pom.xml#L158)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary>
> bom import should also always have <scope>import</scope>
</details>
Done in another patch

---

*[spring-demo-ui/pom.xml, line 47 at r1](https://reviewable.io:443/reviews/vaadin/spring-demo7/1#-KUaRBMdkwhJ0Lbgek6x-r1-47:-KUalz6Y_XLu5SFamrVg:b-896fjx) ([raw file](https://github.com/vaadin/spring-demo7/blob/6797bc3531dbc7298982d5c8f1bca993b633dbe2/spring-demo-ui/pom.xml#L47)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary>
> Is this comment valid anymore? What is the commented out section below?
</details>
Done

---

*[spring-demo-ui/pom.xml, line 41 at r2](https://reviewable.io:443/reviews/vaadin/spring-demo7/1#-KUaRBMdkwhJ0Lbgek6x-r2-41:-KUarJ72EbLOqhdqDv-7:b-lw8iyf) ([raw file](https://github.com/vaadin/spring-demo7/blob/838ea76dd700cabf7371fc658a433bc7cb49e38a/spring-demo-ui/pom.xml#L41)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary>
> see the comment above about BOMs
</details>
Done in another patch

---

*[spring-demo-ui-legacy-boot/pom.xml, line 51 at r1](https://reviewable.io:443/reviews/vaadin/spring-demo7/1#-KUaRBMdkwhJ0Lbgek72-r1-51:-KUaja9xtj_oAAhDQgSZ:b7ft3o3) ([raw file](https://github.com/vaadin/spring-demo7/blob/6797bc3531dbc7298982d5c8f1bca993b633dbe2/spring-demo-ui-legacy-boot/pom.xml#L51)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary>
> Is this still true? What is the problem with 1.4? We should probably fix that and use 1.4.1 rather than making workarounds.
</details>
Done in another pull request

---

*[spring-demo-ui-legacy-boot/pom.xml, line 31 at r2](https://reviewable.io:443/reviews/vaadin/spring-demo7/1#-KUaRBMdkwhJ0Lbgek72-r2-31:-KUajGEVtwlGov3metTw:bhipztj) ([raw file](https://github.com/vaadin/spring-demo7/blob/838ea76dd700cabf7371fc658a433bc7cb49e38a/spring-demo-ui-legacy-boot/pom.xml#L31)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary>
> exclusions and explicit import probably not necessary - I don't think we need anything else than spring-demo-backend and vaadin-spring-boot-starter as explicit compile scope dependencies
</details>
Done in another pull request

---

*[spring-demo-ui-legacy-boot/pom.xml, line 58 at r2](https://reviewable.io:443/reviews/vaadin/spring-demo7/1#-KUaRBMdkwhJ0Lbgek72-r2-58:-KUarKqqV_ptvUldBXQ6:b-lw8iyf) ([raw file](https://github.com/vaadin/spring-demo7/blob/838ea76dd700cabf7371fc658a433bc7cb49e38a/spring-demo-ui-legacy-boot/pom.xml#L58)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary>
> BOM should always be imported with the special approach (type pom, scope import in dependencyManagement IIRC)
</details>
Done in another patch

---

*[spring-demo-ui-legacy-boot/pom.xml, line 70 at r2](https://reviewable.io:443/reviews/vaadin/spring-demo7/1#-KUaRBMdkwhJ0Lbgek72-r2-70:-KUak5UoytDdI_WqvgoJ:b-8xelns) ([raw file](https://github.com/vaadin/spring-demo7/blob/838ea76dd700cabf7371fc658a433bc7cb49e38a/spring-demo-ui-legacy-boot/pom.xml#L70)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary>
> why import type war and classifier classes?
</details>
classes contained in .war are not included into a compilation classpath. This is a workaround  for that.

---

*[spring-demo-ui-legacy-boot/pom.xml, line 93 at r2](https://reviewable.io:443/reviews/vaadin/spring-demo7/1#-KUaRBMdkwhJ0Lbgek72-r2-93:-KUarBUXOJ7RlrxTHxvc:b-lw8iyf) ([raw file](https://github.com/vaadin/spring-demo7/blob/838ea76dd700cabf7371fc658a433bc7cb49e38a/spring-demo-ui-legacy-boot/pom.xml#L93)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary>
> does the project have a production mode module? if not, the related parts can probably be deleted here
</details>
Done in another patch

---

*[spring-demo-ui/src/main/java/com/vaadin/framework7/samples/crud/SampleCrudLogic.java, line 25 at r1](https://reviewable.io:443/reviews/vaadin/spring-demo7/1#-KUaRBMdkwhJ0Lbgek7--r1-25:-KUakQ6h8owO51twNSPI:b4ps2qc) ([raw file](https://github.com/vaadin/spring-demo7/blob/6797bc3531dbc7298982d5c8f1bca993b633dbe2/spring-demo-ui/src/main/java/com/vaadin/framework7/samples/crud/SampleCrudLogic.java#L25)):*
<details><summary><i>Previously, hesara (Henri Sara) wrote…</i></summary>
> Why not a singleton anymore? What scope does this imply without any parameters?
</details>
Commented by mistake.
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spring-demo7/1)*
<!-- Sent from Reviewable.io -->

2016-10-21 11:33 UTC, hesara commented
Reviewed 7 of 12 files at r1, 7 of 7 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spring-demo7/1)*
<!-- Sent from Reviewable.io -->

2016-10-21 12:08 UTC, hesara approved these changes

2016-10-21 12:11 UTC, hesara commented
Reviewed 4 of 13 files at r1, 16 of 16 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/spring-demo7/1)*
<!-- Sent from Reviewable.io -->

2016-10-21 13:20 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vaadin/spring-demo7?pullRequest=1) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/vaadin/spring-demo7?pullRequest=1) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: elmot<br/>:x: hesara

2016-10-21 13:35 UTC, merged